# Assignment-3

## Q1.

In [ ]:
import pandas as pd

data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced",
                       "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K",
                       "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
print(df)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

## Q2. Locate rows 0, 4, 7 and 8 using DataFrame

In [ ]:

selected_rows = df.iloc[[0, 4, 7, 8]]
print(selected_rows)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Q3

In [ ]:
# 1.
print("1. Rows 3 to 7:")
print(df.iloc[3:8])

# 2.
print("\n2. Rows 4 to 8 and columns 2 to 4:")
print(df.iloc[4:9, 2:5])

# 3.
print("\n3. All rows and columns 1 to 3:")
print(df.iloc[:, 1:4])

1. Rows 3 to 7:
   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

2. Rows 4 to 8 and columns 2 to 4:
  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

3. All rows and columns 1 to 3:
  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Q4.

In [ ]:
import kagglehub
path = kagglehub.dataset_download("uciml/iris")

Using Colab cache for faster access to the 'iris' dataset.

In [ ]:
import os

print(path)
print(os.listdir(path))

/kaggle/input/iris
['Iris.csv', 'database.sqlite']

In [ ]:
import pandas as pd

iris_df = pd.read_csv(os.path.join(path, "Iris.csv"))

print("First five rows:")
display(iris_df.head())

First five rows:

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Q5.

In [ ]:
iris_modified = iris_df.drop(index=4)
iris_modified = iris_modified.drop(columns=iris_modified.columns[3])

display(iris_modified)

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

# Q6

In [ ]:
employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01",
                     "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
})

employees.to_csv("employees.csv", index=False)

print("employees.csv created successfully.")
display(employees)

employees.csv created successfully.

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### a)

In [ ]:
print("Shape (rows, columns):", employees.shape)

Shape (rows, columns): (5, 10)

### b)

In [ ]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

### c)

In [ ]:
display(employees.describe())

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

### d)

In [ ]:
print("First 5 rows:")
display(employees.head(5))

print("Last 3 rows:")
display(employees.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### e)

In [ ]:
average_salary = employees["Salary"].mean()
total_bonus = employees["Bonus"].sum()
youngest_age = employees["Age"].min()
highest_rating = employees["Rating"].max()

print("i. Average salary:", average_salary)
print("ii. Total bonus paid:", total_bonus)
print("iii. Youngest employee's age:", youngest_age)
print("iv. Highest performance rating:", highest_rating)

i. Average salary: 60000.0
ii. Total bonus paid: 27500
iii. Youngest employee's age: 28
iv. Highest performance rating: 4.7

### f)

In [ ]:
sorted_employees = employees.sort_values(by="Salary", ascending=False)
display(sorted_employees)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

### g)

In [ ]:
def performance_category(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

employees["Performance_Category"] = employees["Rating"].apply(performance_category)
display(employees)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### h)

In [ ]:
print("Missing values in each column:")
print(employees.isnull().sum())

Missing values in each column:
Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

### i)

In [ ]:
employees.rename(columns={"Employee_ID": "ID"}, inplace=True)
display(employees)

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### j)

In [ ]:
print("i. Employees with more than 5 years of experience:")
display(employees[employees["Years_of_Experience"] > 5])

print("ii. Employees belonging to the IT department:")
display(employees[employees["Department"] == "IT"])

i. Employees with more than 5 years of experience:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

ii. Employees belonging to the IT department:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0

### k)

In [ ]:
employees["Tax"] = employees["Salary"] * 0.10
display(employees)

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

### l)

In [ ]:
output_file = "employees_modified.csv"
employees.to_csv(output_file, index=False)

print(f"Modified DataFrame saved successfully as: {output_file}")
display(employees)

Modified DataFrame saved successfully as: employees_modified.csv

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average